// This file is generated by Slice Machine. Update with care!

import CaseStudyStats from './CaseStudyStats';
import ConnectedProduct from './ConnectedProduct';
import ProductVideo from './ProductVideo';
import TeamMember from './TeamMember';
import Testimonial from './Testimonial';

export {
	CaseStudyStats,
	ConnectedProduct,
	ProductVideo,
	TeamMember,
	Testimonial,
};

export const components = {
	case_study_stats: CaseStudyStats,
	connected_product: ConnectedProduct,
	product_video: ProductVideo,
	team_member: TeamMember,
	testimonial: Testimonial,
};
