// This file is generated by Slice Machine. Update with care!

import ConnectedProduct from './ConnectedProduct';
import ProductVideo from './ProductVideo';
import TeamMember from './TeamMember';

export {
	ConnectedProduct,
	ProductVideo,
	TeamMember,
};

export const components = {
	connected_product: ConnectedProduct,
	product_video: ProductVideo,
	team_member: TeamMember,
};
